# Generated by Django 2.2.4 on 2019-09-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='img',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='Email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewer',
            name='Password',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
