# Generated by Django 2.2.4 on 2019-10-05 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ReviewerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
