# Generated by Django 2.2.4 on 2019-11-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20191012_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.CharField(default='This is a Description', max_length=300),
            preserve_default=False,
        ),
    ]
