# Generated by Django 2.2.5 on 2019-11-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Spam',
            field=models.CharField(default='Not Spam', max_length=1000),
            preserve_default=False,
        ),
    ]
